version: '3.8'
services:
  food-order-mysql:
    image: mysql:8.0
    environment:
      - TZ=Europe/Istanbul
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=FoodOrderApp
    volumes:
      - food-mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.host-name == w2
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
    networks:
      - food-internal

  food-order-redis:
    image: redis:7-alpine
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-}
      --appendonly yes
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - food-redis-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.host-name == w2
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
    networks:
      - food-internal

volumes:
  food-mysql-data:
  food-redis-data:

networks:
  food-internal:
    external: true
