version: '3.8'
services:
  food-order-seller:
    image: ${REGISTRY:-ghcr.io/onuryorulmaz}/food-order-seller:${TAG:-latest}
    environment:
      - TZ=Europe/Istanbul
      - NEXT_PUBLIC_API_BASE_URL=https://${API_DOMAIN}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.host-name == w2
      labels:
        - traefik.enable=true
        - traefik.network=traefik
        - traefik.http.routers.food-seller-http.rule=Host(`${SELLER_DOMAIN}`)
        - traefik.http.routers.food-seller-http.entrypoints=web
        - traefik.http.routers.food-seller-https.rule=Host(`${SELLER_DOMAIN}`)
        - traefik.http.routers.food-seller-https.entrypoints=websecure
        - traefik.http.routers.food-seller-https.tls=true
        - traefik.http.services.food-seller.loadbalancer.server.port=3000
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
    networks:
      - traefik

networks:
  traefik:
    external: true
