// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260314202912_status")]
    partial class status
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Buyer.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<int>("PaymentOptionId")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalProductPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalShipmentDiscount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalShipmentPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserInvoiceAddressId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserShippingAddressId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("MenuId");

                    b.ToTable("BasketItem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItemValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<Guid>("BasketItemId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("MenuOptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MenuOptionValueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BasketItemId");

                    b.HasIndex("MenuOptionId");

                    b.HasIndex("MenuOptionValueId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItemValue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItemValueItemValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<Guid>("BasketItemValueId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("MenuOptionValueOptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MenuOptionValueOptionValueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BasketItemValueId");

                    b.HasIndex("MenuOptionValueOptionId");

                    b.HasIndex("MenuOptionValueOptionValueId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketItemValueItemValue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buyer.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CancellationReason");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CouponCode");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CouponId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DeliveryAddressId");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DiscountAmount");

                    b.Property<Guid?>("InvoiceAddressId")
                        .HasColumnType("char(36)")
                        .HasColumnName("InvoiceAddressId");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Notes");

                    b.Property<int>("PaymentOptionId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentOptionId");

                    b.Property<short>("PaymentStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("PaymentStatusId");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RestaurantId");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SellerId");

                    b.Property<decimal>("ShipmentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ShipmentPrice");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("StatusId");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalPrice");

                    b.Property<decimal>("TotalProductPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalProductPrice");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buyer.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("ItemSnapshotJson")
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("ItemSnapshotJson");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MenuId");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OrderId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalPrice");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UnitPrice");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buyer.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CardAssociation")
                        .HasColumnType("longtext");

                    b.Property<string>("CardLastFourDigits")
                        .HasColumnType("longtext");

                    b.Property<string>("CardType")
                        .HasColumnType("longtext");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PaymentOptionId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderConversationId")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderFraudStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("SellerPayoutAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.UserCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CouponId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OrderId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("UsageCount");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UsedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId", "CouponId");

                    b.ToTable("UserCoupon", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Common.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("AddressType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short?>("InvoiceType")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext");

                    b.Property<Guid>("NeighbourhoodId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TaxArea")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxCode")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TownId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("SellerId");

                    b.HasIndex("UserId");

                    b.ToTable("Address", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3547c056-74d0-436a-83b8-21306946ccad"),
                            AddressLine1 = "Ahmet Yesevi, Bey Sk. No:4/B",
                            AddressName = "Gönderim Adresi",
                            AddressType = (short)4,
                            CityId = new Guid("5d0c385c-810d-4dd6-9462-259183584992"),
                            CreatedDate = new DateTime(2026, 3, 14, 23, 29, 11, 562, DateTimeKind.Local).AddTicks(310),
                            FirstName = "Pizzacı",
                            IsDefault = true,
                            LastName = "Ahmet",
                            Latitude = "40.267317071584884",
                            Longitude = "28.9391322447786",
                            NeighbourhoodId = new Guid("1c2d8a14-38df-448c-8125-14535bf0b7b3"),
                            Phone = "05551112233",
                            RestaurantId = new Guid("3a4d6ba2-593d-4f28-a2ce-89fbbb7fc811"),
                            SellerId = new Guid("bab60c66-11df-4c2d-8fc3-b8702664d9cf"),
                            TownId = new Guid("342b6d4d-42bf-4085-92e7-8d2b51de130a")
                        },
                        new
                        {
                            Id = new Guid("31452b09-7688-4e51-9172-e1cc3e7324f6"),
                            AddressLine1 = "Geçit Mah. 1. Begonya Sok. No: 57 Daire: 6",
                            AddressLine2 = "Oliva Sitesi B Blok",
                            AddressName = "Teslimat Adresi",
                            AddressType = (short)2,
                            CityId = new Guid("5d0c385c-810d-4dd6-9462-259183584992"),
                            CreatedDate = new DateTime(2026, 3, 14, 23, 29, 11, 562, DateTimeKind.Local).AddTicks(3050),
                            FirstName = "Alıcı",
                            InvoiceType = (short)1,
                            IsDefault = true,
                            LastName = "Mehmet",
                            Latitude = "40.26587386663734",
                            Longitude = "28.9617998",
                            NeighbourhoodId = new Guid("1c2d8a14-38df-448c-8125-14535bf0b7b3"),
                            Phone = "05556667788",
                            TownId = new Guid("342b6d4d-42bf-4085-92e7-8d2b51de130a"),
                            UserId = new Guid("67d10056-c978-4e93-89d6-ab078cbab543")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Common.Cuisine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Cuisine", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Common.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ActivationKey")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CardUserKey")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<short?>("SexId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("UserRoleId")
                        .HasColumnType("smallint");

                    b.Property<short>("UserStatusId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6151066b-20e2-4e1b-bbb5-9d10660b5f5f"),
                            ActivationKey = new Guid("ccb6613e-9327-4140-8383-73b9e83b26dd"),
                            BirthDate = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2026, 3, 14, 23, 29, 11, 546, DateTimeKind.Local).AddTicks(7420),
                            Email = "admin@esnaftan.com",
                            FirstName = "Esnaftan",
                            LastName = "Admin",
                            Password = "$2a$12$FSkQpNFCoggkjDbhmQIKLuk2XIF6GF0lCW7nPK7vbJPsV91.zdvzW",
                            PhoneNumber = "05519684748",
                            SexId = (short)1,
                            UserRoleId = (short)1,
                            UserStatusId = (short)1
                        },
                        new
                        {
                            Id = new Guid("c3eac225-2189-42a9-9c6e-c761e55b65d6"),
                            ActivationKey = new Guid("e42dca1e-134d-4b57-9d15-33210704cfae"),
                            BirthDate = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2026, 3, 14, 23, 29, 11, 553, DateTimeKind.Local).AddTicks(8610),
                            Email = "info@pizzaci.com",
                            FirstName = "Pizzacı",
                            LastName = "Ahmet",
                            Password = "$2a$12$FSkQpNFCoggkjDbhmQIKLuk2XIF6GF0lCW7nPK7vbJPsV91.zdvzW",
                            PhoneNumber = "05519684748",
                            SellerId = new Guid("bab60c66-11df-4c2d-8fc3-b8702664d9cf"),
                            SexId = (short)1,
                            UserRoleId = (short)4,
                            UserStatusId = (short)1
                        },
                        new
                        {
                            Id = new Guid("67d10056-c978-4e93-89d6-ab078cbab543"),
                            ActivationKey = new Guid("29396972-5e84-4869-8641-f850ea656c4e"),
                            BirthDate = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2026, 3, 14, 23, 29, 11, 553, DateTimeKind.Local).AddTicks(8820),
                            Email = "alici@gmail.com",
                            FirstName = "Alıcı",
                            LastName = "Mehmet",
                            Password = "$2a$12$FSkQpNFCoggkjDbhmQIKLuk2XIF6GF0lCW7nPK7vbJPsV91.zdvzW",
                            PhoneNumber = "05556667788",
                            SexId = (short)1,
                            UserRoleId = (short)2,
                            UserStatusId = (short)1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Seller.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.CategoryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<short>("ApplicableType")
                        .HasColumnType("smallint")
                        .HasColumnName("ApplicableType");

                    b.Property<int>("BuyQuantity")
                        .HasColumnType("int")
                        .HasColumnName("BuyQuantity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("CurrentUsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("CurrentUsageCount");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EndDate");

                    b.Property<int>("GetQuantity")
                        .HasColumnType("int")
                        .HasColumnName("GetQuantity");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MaxDiscountAmount");

                    b.Property<decimal>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MinOrderAmount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RestaurantId");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SellerId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartDate");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int")
                        .HasColumnName("UsageLimit");

                    b.Property<int?>("UsagePerUser")
                        .HasColumnType("int")
                        .HasColumnName("UsagePerUser");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RestaurantId");

                    b.HasIndex("SellerId");

                    b.ToTable("Coupon", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.CouponCategory", b =>
                {
                    b.Property<Guid>("CouponId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CouponId");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CategoryId");

                    b.HasKey("CouponId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CouponCategory", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.CouponMenu", b =>
                {
                    b.Property<Guid>("CouponId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CouponId");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MenuId");

                    b.HasKey("CouponId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("CouponMenu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MinCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OptionTemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OptionTemplateId");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("OptionTemplateId");

                    b.ToTable("MenuOption", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("MenuOptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OptionTemplateValueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OptionTemplateValueId");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("MenuOptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("MenuOptionValue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValueOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MenuOptionValueId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MinCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OptionTemplateValueOptionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OptionTemplateValueOptionId");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("MenuOptionValueId");

                    b.ToTable("MenuOptionValueOption", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValueOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("MenuOptionValueOptionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OptionTemplateValueOptionValueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OptionTemplateValueOptionValueId");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("MenuOptionValueOptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("MenuOptionValueOptionValue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int")
                        .HasColumnName("MaxCount");

                    b.Property<int>("MinCount")
                        .HasColumnType("int")
                        .HasColumnName("MinCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("OrderIndex");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RestaurantId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("OptionTemplate", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("OptionTemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OptionTemplateId");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("OrderIndex");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProductId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OptionTemplateId");

                    b.HasIndex("ProductId");

                    b.ToTable("OptionTemplateValue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValueOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int")
                        .HasColumnName("MaxCount");

                    b.Property<int>("MinCount")
                        .HasColumnType("int")
                        .HasColumnName("MinCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<Guid>("OptionTemplateValueId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OptionTemplateValueId");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("OrderIndex");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OptionTemplateValueId");

                    b.ToTable("OptionTemplateValueOption", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValueOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("OptionTemplateValueOptionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("OptionTemplateValueOptionId");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("OrderIndex");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProductId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("OptionTemplateValueOptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("OptionTemplateValueOptionValue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("CuisineId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.Property<int>("MinCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttribute", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("ProductAttributeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributeValue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CoverImage");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsOpen");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("Longitude");

                    b.Property<int>("MaxDeliveryTime")
                        .HasColumnType("int")
                        .HasColumnName("MaxDeliveryTime");

                    b.Property<int>("MinDeliveryTime")
                        .HasColumnType("int")
                        .HasColumnName("MinDeliveryTime");

                    b.Property<decimal>("MinimumOrderPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MinimumOrderPrice");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("Rating");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int")
                        .HasColumnName("RatingCount");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SellerId");

                    b.Property<string>("ServiceAreaPolygonWkt")
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("ServiceAreaPolygonWkt");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Restaurant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a4d6ba2-593d-4f28-a2ce-89fbbb7fc811"),
                            CoverImage = "https://cdn.getiryemek.com/restaurants/1741075067957_1125x522.webp",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Süper lezzetli pizzalar, hızlı teslimat!",
                            Email = "a@a.com",
                            IsActive = false,
                            IsOpen = false,
                            MaxDeliveryTime = 45,
                            MinDeliveryTime = 25,
                            MinimumOrderPrice = 250m,
                            Name = "Pizzacı Ahmet",
                            Phone = "05551112233",
                            Rating = 0m,
                            RatingCount = 0,
                            SellerId = new Guid("bab60c66-11df-4c2d-8fc3-b8702664d9cf")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Seller.RestaurantCdnUpdateQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ErrorMessage");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ProcessedAt");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RestaurantId");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("RetryCount");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("StatusId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("StatusId", "CreatedDate");

                    b.ToTable("RestaurantCdnUpdateQueue", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.RestaurantWorkingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "DayOfWeek");

                    b.ToTable("RestaurantWorkingHour", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid?>("ExtraId1")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ExtraId2")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ExtraId3")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsStart")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ScheduleJobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("ScheduledTask", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("longtext");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("longtext");

                    b.Property<short>("CompanyStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("CompanyType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEInvoiceAvaible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaxArea")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Seller", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bab60c66-11df-4c2d-8fc3-b8702664d9cf"),
                            CompanyStatus = (short)1,
                            CompanyType = (short)2,
                            CreatedDate = new DateTime(2026, 3, 14, 23, 29, 11, 554, DateTimeKind.Local).AddTicks(4560),
                            IBAN = "TR260006266822193294982978",
                            IsEInvoiceAvaible = true,
                            LegalName = "Pizzacı Ahmet Ltd. Şti.",
                            Name = "Pizzacı Ahmet",
                            TaxArea = "Nilüfer",
                            TaxCode = "1234567890"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Seller.SellerDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Key1")
                        .HasColumnType("int");

                    b.Property<int?>("Key2")
                        .HasColumnType("int");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ValueDec")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int");

                    b.Property<string>("ValueStr")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SellerDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EndDate");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Notes");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PaidAmount");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RestaurantId");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SellerId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartDate");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("StatusId");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("SubscriptionPlanId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("SellerId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seller.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<int>("MaxRestaurants")
                        .HasColumnType("int")
                        .HasColumnName("MaxRestaurants");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MonthlyPrice");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<short>("PlanType")
                        .HasColumnType("smallint")
                        .HasColumnName("PlanType");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlan", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItem", b =>
                {
                    b.HasOne("Domain.Entities.Buyer.Basket", "Basket")
                        .WithMany("BasketItems")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItemValue", b =>
                {
                    b.HasOne("Domain.Entities.Buyer.BasketItem", "BasketItem")
                        .WithMany("BasketItemValues")
                        .HasForeignKey("BasketItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.MenuOption", "MenuOption")
                        .WithMany()
                        .HasForeignKey("MenuOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.MenuOptionValue", "MenuOptionValue")
                        .WithMany()
                        .HasForeignKey("MenuOptionValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketItem");

                    b.Navigation("MenuOption");

                    b.Navigation("MenuOptionValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItemValueItemValue", b =>
                {
                    b.HasOne("Domain.Entities.Buyer.BasketItemValue", "BasketItemValue")
                        .WithMany("BasketItemValueItemValues")
                        .HasForeignKey("BasketItemValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.MenuOptionValueOption", "MenuOptionValueOption")
                        .WithMany()
                        .HasForeignKey("MenuOptionValueOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.MenuOptionValueOptionValue", "MenuOptionValueOptionValue")
                        .WithMany()
                        .HasForeignKey("MenuOptionValueOptionValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasketItemValue");

                    b.Navigation("MenuOptionValueOption");

                    b.Navigation("MenuOptionValueOptionValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Buyer.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.OrderStatusHistory", b =>
                {
                    b.HasOne("Domain.Entities.Buyer.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Buyer.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.UserCoupon", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Buyer.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("Domain.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Common.Address", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId");

                    b.HasOne("Domain.Entities.Seller.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId");

                    b.HasOne("Domain.Entities.Common.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Restaurant");

                    b.Navigation("Seller");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Category", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Entities.Seller.CategoryDetail", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Category", "Category")
                        .WithMany("CategoryDetails")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Coupon", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId");

                    b.HasOne("Domain.Entities.Seller.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Domain.Entities.Seller.CouponCategory", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Coupon", "Coupon")
                        .WithMany("CouponCategories")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Domain.Entities.Seller.CouponMenu", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Coupon", "Coupon")
                        .WithMany("CouponMenus")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Menu", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOption", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Menu", "Menu")
                        .WithMany("MenuOptions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.OptionTemplate", "OptionTemplate")
                        .WithMany()
                        .HasForeignKey("OptionTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Menu");

                    b.Navigation("OptionTemplate");
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValue", b =>
                {
                    b.HasOne("Domain.Entities.Seller.MenuOption", "MenuOption")
                        .WithMany("MenuOptionValues")
                        .HasForeignKey("MenuOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValueOption", b =>
                {
                    b.HasOne("Domain.Entities.Seller.MenuOptionValue", "MenuOptionValue")
                        .WithMany("MenuOptionValueOptions")
                        .HasForeignKey("MenuOptionValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuOptionValue");
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValueOptionValue", b =>
                {
                    b.HasOne("Domain.Entities.Seller.MenuOptionValueOption", "MenuOptionValueOption")
                        .WithMany("MenuOptionValueOptionValues")
                        .HasForeignKey("MenuOptionValueOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuOptionValueOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplate", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValue", b =>
                {
                    b.HasOne("Domain.Entities.Seller.OptionTemplate", "OptionTemplate")
                        .WithMany("OptionTemplateValues")
                        .HasForeignKey("OptionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionTemplate");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValueOption", b =>
                {
                    b.HasOne("Domain.Entities.Seller.OptionTemplateValue", "OptionTemplateValue")
                        .WithMany("OptionTemplateValueOptions")
                        .HasForeignKey("OptionTemplateValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionTemplateValue");
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValueOptionValue", b =>
                {
                    b.HasOne("Domain.Entities.Seller.OptionTemplateValueOption", "OptionTemplateValueOption")
                        .WithMany("OptionTemplateValueOptionValues")
                        .HasForeignKey("OptionTemplateValueOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionTemplateValueOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Product", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Entities.Seller.ProductAttribute", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Seller.ProductAttributeValue", b =>
                {
                    b.HasOne("Domain.Entities.Seller.ProductAttribute", "ProductAttribute")
                        .WithMany("ProductAttributeValues")
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("Domain.Entities.Seller.RestaurantWorkingHour", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Subscription", b =>
                {
                    b.HasOne("Domain.Entities.Seller.Restaurant", "Restaurant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seller.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Seller");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.Basket", b =>
                {
                    b.Navigation("BasketItems");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItem", b =>
                {
                    b.Navigation("BasketItemValues");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.BasketItemValue", b =>
                {
                    b.Navigation("BasketItemValueItemValues");
                });

            modelBuilder.Entity("Domain.Entities.Buyer.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Category", b =>
                {
                    b.Navigation("CategoryDetails");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Coupon", b =>
                {
                    b.Navigation("CouponCategories");

                    b.Navigation("CouponMenus");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Menu", b =>
                {
                    b.Navigation("MenuOptions");
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOption", b =>
                {
                    b.Navigation("MenuOptionValues");
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValue", b =>
                {
                    b.Navigation("MenuOptionValueOptions");
                });

            modelBuilder.Entity("Domain.Entities.Seller.MenuOptionValueOption", b =>
                {
                    b.Navigation("MenuOptionValueOptionValues");
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplate", b =>
                {
                    b.Navigation("OptionTemplateValues");
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValue", b =>
                {
                    b.Navigation("OptionTemplateValueOptions");
                });

            modelBuilder.Entity("Domain.Entities.Seller.OptionTemplateValueOption", b =>
                {
                    b.Navigation("OptionTemplateValueOptionValues");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Product", b =>
                {
                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("Domain.Entities.Seller.ProductAttribute", b =>
                {
                    b.Navigation("ProductAttributeValues");
                });

            modelBuilder.Entity("Domain.Entities.Seller.Restaurant", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Seller.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
